language: node_js
env:
  global:
  - NODE_ENV=production
cache: yarn
node_js:
- 8
install:
- yarn
script:
- echo -e "TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG \n TRAVIS_BUILD_DIR=$TRAVIS_BUILD_DIR
  \n TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST \n TRAVIS_PULL_REQUEST_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH
  \n TRAVIS_BRANCH=$TRAVIS_BRANCH \n TRAVIS_TAG=$TRAVIS_TAG \n "
- yarn run build
notifications:
  slack:
    secure: Yxr6Ty78cS1H1AStLMcgI7tQpYOC5zCUmWW2hNEmRNJyUkZlY1FCZK5liEB9ZSAo0QKWCCMOcTCS0vFDfeUXgX1nMLXUW4w7Skps4alfgUDXPk6hnZP8emkbAUbhI2KJxu6SfNNnZS5e79GsTolIZWr5+LXACjoUeKcMy/HfnO9QOJ0pH61k96v7uU79mL5nmYSreBoYT0YaKB7IY1n5c2wJQEcUCaUTHUWZ0dzziiLOv4u61VNiHga22aV77ur1vnWXbcF7Uyi8fFiqL0CnORIMTaBAKSVrcQW08EFoDUA2UjIMRQzvNkKTgkZFwLrWJuTQ/CjJkZ7q2JWu3D3zH9frht9MLN7E0C/N+MI6VBAlDM/jQ9gON2/BFte/XaWHi3/yEvJvVxXMnp6lbj0JUZYchD32Lu/xTBagT2x0p2z1jwO3AXKaDmeoXgH4brNEarDKWMfFnCQ/J8aS0VaEsyj3fcB4b6k5GAZDX3KZBccDT99FulpgAZyqY7ZuXet8Wmum9ssRSllBUZYeAZGcjCET/Dq7UdZSMrUPEwyhTAa2rWwnRLrz/0YELsceGD9Ba3aD0sTLOUafntgYbtzxdr/H/wbjL6eleCLyp4HbuAXnA7Q2/bzVmQ2+B0msA8TKdU10JcKOvtlgqtSBW+NAOqvoJclTWVCArUDT597vjy0=
