version: '2'
services:
  app:
    build: .
  nginx:
    image: nginx:latest
    depends_on:
      - node
    volumes_from:
      - app
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - node
    ports:
      - "3000:80"
    restart: always
  node:
    image: node:latest
    depends_on:
      - redis
      - mongo
    volumes_from:
      - app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    links:
      - redis
      - mongo
    working_dir: /app
    command: node dist
    restart: always
  redis:
    image: redis:latest
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
