version: '3'
services:
  nginx:
    image: nginx:latest
    depends_on:
      - node
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html
    links:
      - node
    ports:
      - "3000:80"
    restart: always
  node:
    build: .
    depends_on:
      - redis
      - mongo
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    links:
      - redis
      - mongo
    restart: always
  redis:
    image: redis:latest
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
